### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Ralino** [mutaphysis/qml-tools#2]
Hello,

I would like to use and extend your qml coverage tool, but I noticed that you have not specified a license, so I (and everyone else) am not [legally allowed to use it](https://choosealicense.com/no-permission/).

In case that this is not on purpose, could you maybe add a license (e.g. [MIT](https://choosealicense.com/licenses/mit/))?

Thanks!

**Comment by mutaphysis** [comment]
Done
